format = """
[](#b4befe)\
$os\
$username\
[](bg:#74c7ec fg:#b4befe)\
$directory\
[](fg:#5c5f77 bg:#74c7ec)\
$git_branch\
$git_status\
[](fg:#7f849c bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#94e2d5)\
$time\
[ ](fg:#94e2d5)\
"""

[username]
show_always = true
style_user = "bg:#b4befe"
style_root = "bg:#b4befe"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#9A348E"
disabled = true 

[directory]
style = "bg:#74c7ec"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#f2cdcd"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#f2cdcd"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#f2cdcd"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#f2cdcd"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#f2cdcd"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#f2cdcd"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#f2cdcd"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#f2cdcd"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#f2cdcd"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#f2cdcd"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#f2cdcd"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#f2cdcd"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#f2cdcd"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#f2cdcd"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#f2cdcd"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" 
style = "bg:#94e2d5"
format = '[ ♥ $time ]($style)'
